"""Initial tables for users workflow records catalogs

Revision ID: 224ba6bb447d
Revises: 
Create Date: 2025-12-14 18:04:25.447287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '224ba6bb447d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create schemas for bounded contexts
    op.execute('CREATE SCHEMA IF NOT EXISTS catalogs')
    op.execute('CREATE SCHEMA IF NOT EXISTS records')
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    op.execute('CREATE SCHEMA IF NOT EXISTS workflow')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpt_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalogs'
    )
    op.create_index(op.f('ix_catalogs_cpt_codes_code'), 'cpt_codes', ['code'], unique=True, schema='catalogs')
    op.create_table('icd10_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='catalogs'
    )
    op.create_index(op.f('ix_catalogs_icd10_codes_code'), 'icd10_codes', ['code'], unique=True, schema='catalogs')
    op.create_table('medical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_category', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='records'
    )
    op.create_index(op.f('ix_records_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False, schema='records')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_email'), 'users', ['email'], unique=True, schema='users')
    op.create_table('coding_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='workflow'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coding_tasks', schema='workflow')
    op.drop_index(op.f('ix_users_users_email'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    op.drop_index(op.f('ix_records_medical_records_patient_id'), table_name='medical_records', schema='records')
    op.drop_table('medical_records', schema='records')
    op.drop_index(op.f('ix_catalogs_icd10_codes_code'), table_name='icd10_codes', schema='catalogs')
    op.drop_table('icd10_codes', schema='catalogs')
    op.drop_index(op.f('ix_catalogs_cpt_codes_code'), table_name='cpt_codes', schema='catalogs')
    op.drop_table('cpt_codes', schema='catalogs')
    # ### end Alembic commands ###

    # Drop schemas
    op.execute('DROP SCHEMA IF EXISTS workflow')
    op.execute('DROP SCHEMA IF EXISTS users')
    op.execute('DROP SCHEMA IF EXISTS records')
    op.execute('DROP SCHEMA IF EXISTS catalogs')
